<a href="https://colab.research.google.com/github/Shivam24012001/Python_Basic/blob/main/Eden's__Dried_Delights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Eden Dried Delights** is a specialty store that offers a wide selection of dried fruits, conveniently packaged in 100g packs. You have been provided with a dataset containing the sales data of Eden Dried Delights in the below link. This is a cumulative sales of each of the product being sold by the company in a week.


url: "https://raw.githubusercontent.com/Invact-Abhay/DOE/refs/heads/main/Eden's%20Dried_Delights%20-%20Data.csv"

# **PF1.1**

***Task 1: Import the pandas library.***

In [2]:
import pandas as pd

***Task 2: Create a DataFrame named 'data' from the given URL and then print the first 5 rows using head() function.***

In [3]:
data=pd.read_csv("https://raw.githubusercontent.com/Invact-Abhay/DOE/refs/heads/main/Eden's%20Dried_Delights%20-%20Data.csv")
data.head()

,Product,ProductCategory,UnitsSold,UnitSellingPrice,DiscountPercentage
0,Raisins,Dried Fruits,30,40,0.05
1,Dried Figs,Dried Fruits,24,110,0.05
2,Dried Dates,Dried Fruits,40,52,0.05
3,Almonds,Nuts,42,80,0.05
4,Dried Cranberries,Dried Fruits,15,100,0.05

***Task 3: Add a column named 'GrossSales' and calculate the gross sales for each product by multiplying the unit selling price by the units sold.***

In [5]:
data['GrossSales']=data['UnitsSold']*data['UnitSellingPrice']
data.head()

,Product,ProductCategory,UnitsSold,UnitSellingPrice,DiscountPercentage,GrossSales
0,Raisins,Dried Fruits,30,40,0.05,1200
1,Dried Figs,Dried Fruits,24,110,0.05,2640
2,Dried Dates,Dried Fruits,40,52,0.05,2080
3,Almonds,Nuts,42,80,0.05,3360
4,Dried Cranberries,Dried Fruits,15,100,0.05,1500

***Task 4: Add a column named 'DiscountAmount' and calculate the discount amount for each product by multiplying the gross sales by the discount percentage.***

In [6]:
data['DiscountAmount']=data['GrossSales']*data['DiscountPercentage']
data.head()

,Product,ProductCategory,UnitsSold,UnitSellingPrice,DiscountPercentage,GrossSales,DiscountAmount
0,Raisins,Dried Fruits,30,40,0.05,1200,60.0
1,Dried Figs,Dried Fruits,24,110,0.05,2640,132.0
2,Dried Dates,Dried Fruits,40,52,0.05,2080,104.0
3,Almonds,Nuts,42,80,0.05,3360,168.0
4,Dried Cranberries,Dried Fruits,15,100,0.05,1500,75.0

***Task 5: Add a column named 'Net Sales' and calculate the net sales for each product by subtracting the discount amount from the gross sales.***

In [7]:
data['NetSales']=data['GrossSales']-data['DiscountAmount']
data

,Product,ProductCategory,UnitsSold,UnitSellingPrice,DiscountPercentage,GrossSales,DiscountAmount,NetSales
0,Raisins,Dried Fruits,30,40,0.05,1200,60.0,1140.0
1,Dried Figs,Dried Fruits,24,110,0.05,2640,132.0,2508.0
2,Dried Dates,Dried Fruits,40,52,0.05,2080,104.0,1976.0
3,Almonds,Nuts,42,80,0.05,3360,168.0,3192.0
4,Dried Cranberries,Dried Fruits,15,100,0.05,1500,75.0,1425.0
5,Dried Mango,Dried Fruits,18,175,0.05,3150,157.5,2992.5
6,Dried Pineapple,Dried Fruits,16,180,0.05,2880,144.0,2736.0
7,Cashews,Nuts,45,110,0.05,4950,247.5,4702.5
8,Walnut,Nuts,30,130,0.05,3900,195.0,3705.0
9,Dried Cherries,Dried Fruits,20,210,0.05,4200,210.0,3990.0
10,Dried Blueberries,Dried Fruits,15,290,0.10,4350,435.0,3915.0
11,Dried Papaya,Dried Fruits,14,150,0.05,2100,105.0,1995.0
12,Dried Strawberries,Dried Fruits,28,157,0.05,4396,219.8,4176.2
13,Dried Mulberries,Dried Fruits,10,300,0.10,3000,300.0,2700.0
14,Dried Pears,Dried Fruits,9,130,0.05,1170,58.5,1111.5
15,Dried Kiwi,Dried Fruits,12,99,0.05,1188,59.4,1128.6
16,Prunes,Dried Fruits,7,325,0.10,2275,227.5,2047.5

# **PF1.2**

***Task 6: Determine the total number of products sold by Eden Dried Delights.***

In [9]:
data['Product'].count()

np.int64(17)

***Task 7: Calculate the total revenue of Eden Dried Delights.***

In [10]:
data['NetSales'].sum()

np.float64(45440.8)

***Task 8: Find the maximum unit selling price among the products***

In [12]:
data['UnitSellingPrice'].max()

325

***Task 9: Find the minimum unit selling price among the products.***

In [13]:
data['UnitSellingPrice'].min()

40

***Task 10: What is the average discount % provided for the period.***

In [17]:
data['DiscountPercentage'].mean()

np.float64(0.058823529411764705)

***Task 11: What is the average discount amount per product.***

In [18]:
data['DiscountAmount'].mean()

np.float64(170.48235294117646)

***Task 12: What is the maximum discount percentage provided by the company.***

In [19]:
data['DiscountPercentage'].max()

0.1